#!/bin/sh

echo "-----"
echo "Avorion Server Deploy"
echo "-----"
echo ""

echo "\n....removing old server files..."
rm -rf /srv/avorion
unset GIT_DIR
echo "\n....cloning repo..."
git clone /var/git/avorion-server.git /srv/avorion
echo "\n....updating permissions..."
chmod ug+x /srv/avorion/bin/*

### Setup HTTP Server

echo "\n....syncing web files..."
rm -rf /var/www/

# Sync files
rsync -rv /srv/avorion/http-server/ /var/www

# Start simpleHttpServer
/bin/bash /srv/avorion/bin/boot-http.sh

# rsync -rv /tmp/wp-content/ /srv/www/wordpress-live/wp-content


# printf "\n...fixing permissions on wp_content..."
# chown -R nginx:nginx /srv/www/wordpress-live/wp-content

echo ""
echo "-----"
echo "deploy successful"
echo "------"